name: Update

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  updating:
    runs-on: ubuntu-latest

    container:
        image: archlinux:latest
        options: --privileged

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Installing dependencies
        run: pacman -Syu base-devel git github-cli pacman-contrib sudo fakeroot --noconfirm --needed
      - name: Cloning repo
        run: git clone https://github.com/tcet-opensource/tcet-linux-pkgbuild.git
      - name: Downloading Script
        run: curl https://raw.githubusercontent.com/tcet-opensource/tcet-linux-automation-scripts/main/updsum.sh -o updsum.sh
      - name: Making exectuable
        run: |
            ls -al
            chmod -R 777 .
            chmod +777 updsum.sh
            ls -al
      - name: Creating new User
        run: |
            useradd non_root && mkdir /home/non_root && chown -R non_root:non_root /home/non_root
            echo 'non_root ALL=NOPASSWD: ALL' >> /etc/sudoers
            ls -al
      - name: Updating Shasum
        run: sudo -u non_root ./updsum.sh
      - name: Removing Script
        run: rm -rf updsum.sh
      - name: ls
        run: ls -al
      - name: cd
        run: cd tcet-linux-pkgbuild
      - name: ls
        run: ls -al
      - name: Commit and Push Changes
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Formatted the code'
          force: true
